# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e46e9746ee21aa6e9af166b5c016a000dd6af2d8060bae59e7025d6297e842c68c7157892a2949ac9e20f790e07e62c177174bc1ce7c131ef15f73bed1b4450

test:
  secret_key_base: 76286f71de636595033821635e2a6c89e9a9a77de45e0b90ba81bd3573503cb697718f7d5232c78e1f59be12eef99e9a48fb663dcea923b0f86d86f8424d8dc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
